### ISSUE TITLE
Basics

### ISSUE THREAD

**Issue by datajohnson** [icefoganalytics/weather-transfer-files#1]
- FTP Server (Whatever Linux you use will likely have something simple) running on :22
- HTTP Server (NGINX) running on :80

2 FTP accounts, each with write access to a directory, NGINX directory listing setup pointing to those 2 different directories

NGINX serving files from directories defined in nginx.conf

BASIC IDEA: people with FTP accounts can write to those directories and anybody can read from them

**Comment by datajohnson** [comment]
Best case scenario has the FTP passwords coming from .env so Kubernetes can inject them at runtime.

**Comment by klondikemarlen** [comment]
# User Story
- Users from group A can save files to a Directory A that anybody can read.
- Users from group B can save files to a Directory B that anybody can read.

# Implementation Details
- Preferred method of saving files is FTP.
- Preferred method of listing files in Directories A/B is using NGINX directory index listing.
